import type { Metadata, Viewport } from "next";
import "./globals.css";
import { GeistSans } from "@/fonts";
import { Toaster } from "sonner";
import SessionProvider from "@/context/SessionProvider";

export const metadata: Metadata = {
  title: "Gym track",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: '#060708',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  colorScheme: 'dark',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} antialiased`}>
        <SessionProvider>
          {children}
        </SessionProvider>
        <Toaster richColors position="top-center" closeButton />
      </body>
    </html>
  );
}
