import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "@/fonts";
import { Toaster } from "sonner";
import AppLayout from "@/components/AppLayout/AppLayout";

export const metadata: Metadata = {
  title: "Gym track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} antialiased`}>
        <AppLayout>
          {children}
        </AppLayout>
        <Toaster richColors position="bottom-left" />
      </body>
    </html>
  );
}
